// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorFutDep.App.Persistencia;

namespace TorFutDep.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TorFutDep.App.Dominio.Arbitro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Arbitro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arbitros");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Desempeño_Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cantidad_de_Partidos_Empatados")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_de_Partidos_Ganados")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_de_Partidos_Jugados")
                        .HasColumnType("int");

                    b.Property<int>("Goles_A_Favor")
                        .HasColumnType("int");

                    b.Property<int>("Goles_En_Contra")
                        .HasColumnType("int");

                    b.Property<int?>("N_EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("N_EquipoId");

                    b.ToTable("Desempeño_Equipos");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Director_Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Director_Tecnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directores_Tecnicos");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("N_Director_TecnicoId")
                        .HasColumnType("int");

                    b.Property<int?>("N_MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Equipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("N_Director_TecnicoId");

                    b.HasIndex("N_MunicipioId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("N_MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Estadio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("N_MunicipioId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("N_EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Jugador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipos_Posiciones")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("N_EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre_Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Novedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("N_EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("N_EstadioId")
                        .HasColumnType("int");

                    b.Property<int?>("N_JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("N_Tipo_Novedad")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("N_EquipoId");

                    b.HasIndex("N_EstadioId");

                    b.HasIndex("N_JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Equipo_LocalId")
                        .HasColumnType("int");

                    b.Property<int?>("Equipo_VisitanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Marcador_Final")
                        .HasColumnType("int");

                    b.Property<int>("Marcador_Inicial_Local")
                        .HasColumnType("int");

                    b.Property<int>("Marcador_Inicial_Visitante")
                        .HasColumnType("int");

                    b.Property<int?>("N_ArbitroId")
                        .HasColumnType("int");

                    b.Property<int?>("N_EstadioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Equipo_LocalId");

                    b.HasIndex("Equipo_VisitanteId");

                    b.HasIndex("N_ArbitroId");

                    b.HasIndex("N_EstadioId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Desempeño_Equipo", b =>
                {
                    b.HasOne("TorFutDep.App.Dominio.Equipo", "N_Equipo")
                        .WithMany()
                        .HasForeignKey("N_EquipoId");

                    b.Navigation("N_Equipo");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Equipo", b =>
                {
                    b.HasOne("TorFutDep.App.Dominio.Director_Tecnico", "N_Director_Tecnico")
                        .WithMany()
                        .HasForeignKey("N_Director_TecnicoId");

                    b.HasOne("TorFutDep.App.Dominio.Municipio", "N_Municipio")
                        .WithMany()
                        .HasForeignKey("N_MunicipioId");

                    b.Navigation("N_Director_Tecnico");

                    b.Navigation("N_Municipio");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Estadio", b =>
                {
                    b.HasOne("TorFutDep.App.Dominio.Municipio", "N_Municipio")
                        .WithMany()
                        .HasForeignKey("N_MunicipioId");

                    b.Navigation("N_Municipio");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Jugador", b =>
                {
                    b.HasOne("TorFutDep.App.Dominio.Equipo", "N_Equipo")
                        .WithMany()
                        .HasForeignKey("N_EquipoId");

                    b.Navigation("N_Equipo");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Novedad", b =>
                {
                    b.HasOne("TorFutDep.App.Dominio.Equipo", "N_Equipo")
                        .WithMany()
                        .HasForeignKey("N_EquipoId");

                    b.HasOne("TorFutDep.App.Dominio.Estadio", "N_Estadio")
                        .WithMany()
                        .HasForeignKey("N_EstadioId");

                    b.HasOne("TorFutDep.App.Dominio.Jugador", "N_Jugador")
                        .WithMany()
                        .HasForeignKey("N_JugadorId");

                    b.HasOne("TorFutDep.App.Dominio.Partido", null)
                        .WithMany("Novedades")
                        .HasForeignKey("PartidoId");

                    b.Navigation("N_Equipo");

                    b.Navigation("N_Estadio");

                    b.Navigation("N_Jugador");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Partido", b =>
                {
                    b.HasOne("TorFutDep.App.Dominio.Equipo", "Equipo_Local")
                        .WithMany()
                        .HasForeignKey("Equipo_LocalId");

                    b.HasOne("TorFutDep.App.Dominio.Equipo", "Equipo_Visitante")
                        .WithMany()
                        .HasForeignKey("Equipo_VisitanteId");

                    b.HasOne("TorFutDep.App.Dominio.Arbitro", "N_Arbitro")
                        .WithMany()
                        .HasForeignKey("N_ArbitroId");

                    b.HasOne("TorFutDep.App.Dominio.Estadio", "N_Estadio")
                        .WithMany()
                        .HasForeignKey("N_EstadioId");

                    b.Navigation("Equipo_Local");

                    b.Navigation("Equipo_Visitante");

                    b.Navigation("N_Arbitro");

                    b.Navigation("N_Estadio");
                });

            modelBuilder.Entity("TorFutDep.App.Dominio.Partido", b =>
                {
                    b.Navigation("Novedades");
                });
#pragma warning restore 612, 618
        }
    }
}
